version: '3.9'

services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - ./app/:/src/
    env_file:
      - ./.env.dev
    depends_on:
      - database   
    
  database:
    image: postgres:14.6-alpine
    environment:
      - POSTGRES_USER=cook_book
      - POSTGRES_PASSWORD=cook_book
      - POSTGRES_DB=cook_book_dev
    volumes:
      - pg-data:/var/lib/postgresql/data/

volumes:
    pg-data:
