version: '3.9'

services:
  backend:
    image: cook_book
    build:
      context: cook_book
      dockerfile: Dockerfile
    expose:
      - 8000
    command: sh -c "python manage.py migrate &&
             gunicorn cook_book.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static_volume:/cook_book/static
    env_file:
      - ./.env.prod
    depends_on:
      - database
  database:
    image: postgres:14.6-alpine
    env_file:
      - ./.env.db
    volumes:
      - pg-data:/var/lib/postgres/data
  server:
    image: nginx:latest
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend
    volumes:
      - static_volume:/cook_book/static
volumes:
    pg-data:
    static_volume:
    media_volume: